# Generated by Django 4.2.29 on 2026-03-16 04:11

import apps.files.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255, unique=True)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.files.models.user_directory_path)),
                ('special_link_uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
            ],
        ),
    ]
