# Generated by Django 4.2.29 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='stored_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
